// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCScMU_4qlajHQsl8RvxkqkiZ8Dtjdv8hw',
    appId: '1:777582167550:web:5ddc5d48352679d0d16caf',
    messagingSenderId: '777582167550',
    projectId: 'tourism-app-7b702',
    authDomain: 'tourism-app-7b702.firebaseapp.com',
    storageBucket: 'tourism-app-7b702.appspot.com',
    measurementId: 'G-T8PBCNBFBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmWL1NUFoVA9v26K4haDJZCF8lnfp9vig',
    appId: '1:777582167550:android:6f800e4585dbf077d16caf',
    messagingSenderId: '777582167550',
    projectId: 'tourism-app-7b702',
    storageBucket: 'tourism-app-7b702.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVktb8BzpLni1OLHo0MK_wQkEheq6H2oI',
    appId: '1:777582167550:ios:ec3aec0fb24a7cf6d16caf',
    messagingSenderId: '777582167550',
    projectId: 'tourism-app-7b702',
    storageBucket: 'tourism-app-7b702.appspot.com',
    iosClientId: '777582167550-9p2upb08a7e1ta1vti5v9fhsq5cqcv5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.first',
  );
}
